version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - '.:/app'
    environment:
      REACT_APP_FP_URL: http://api.example.com
      REACT_APP_FP_LICENCE_KEY: "kjsfdnfvlkwdsmfvklwdsvc"