name: CI FLOW

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        description: 'AWS access key id'
        required: true
      AWS_SECRET_ACCESS_KEY:
        description: 'AWS secret access key'
        required: true
      AWS_REGION:
        description: 'AWS region'
        required: true
      GH_CUSTOM_TOKEN:
        description: 'Github token'
        required: true
    inputs:
      is_workflow:
        required: true
        type: boolean
        default: false
      owner:
        required: true
        type: string
      service:
        required: true
        type: string
      project:
        required: true
        type: string
      region:
        type: string
      repository:
        required: true
        type: string
      instance_type:
        required: true
        type: string
      hostname-format:
        required: true
        type: string
      port:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
      docker_compose_file:
        type: string
      buildCommand:
        type: string
      unitTestCommand:
        type: string
      e2eTestCommand:
        type: string
      app_secret:
        type: string
      probe_url:
        type: string
      namespace:
        type: string

permissions:
  id-token: write
  contents: read

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  info:
    name: CI workflow for ${{ inputs.service }}
    runs-on: ubuntu-latest
    steps:
      - name: Initialize environments
        run: |
          echo "Service name : ${{ inputs.service }}"
  build:
    name: "Build"
    permissions: write-all
    needs: [ info ]
    uses: calcot/calcot-devops/.github/workflows/build.yaml@main
    with:
      project: ${{ inputs.project }}
      dockerfile: ${{ inputs.dockerfile }}
      unitTestCommand: ${{ inputs.unitTestCommand }}
      e2eTestCommand: ${{ inputs.e2eTestCommand }}

  setups:
    name: "DevOps"
    runs-on: ubuntu-latest
    needs: [ build, info ]
    steps:
      - name: Clone DevOps repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: ${{ inputs.owner }}
          repository: ${{ inputs.repository }}
          access-token: ${{ secrets.GH_CUSTOM_TOKEN }}
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: ${{ inputs.repository }}
      - name: Upload Repo to Artifact
        uses: actions/upload-artifact@master
        with:
          name: cloud-scripts
          path: ${{ inputs.repository }}

  ci:
    name: "CI"
    permissions: write-all
    needs: [ setups ]
    uses: calcot/calcot-devops/.github/workflows/aws-k8-ci.yaml@main
    with:
      is_workflow: true
      project: ${{ inputs.project }}
      region: ${{ inputs.region }}
      service: ${{ inputs.service }}
      repository: ${{ inputs.repository }}
      hostname-format: ${{ inputs.hostname-format }}
      port: ${{ inputs.port }}
      dockerfile: ${{ inputs.dockerfile }}
      docker_compose_file: ${{ inputs.docker_compose_file }}
      app_secret: ${{ inputs.app_secret }}
      probe_url: ${{ inputs.probe_url }}
      namespace: ${{ inputs.namespace }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      GH_CUSTOM_TOKEN: ${{ secrets.GH_CUSTOM_TOKEN }}